import Phaser from 'phaser';
import { AnimalBehavior, type BehaviorSnapshot } from '../simulation/behavior';
import type { PastureZone } from '../simulation/farm-layout';
import type { AnimalState } from '../types';
import { classifySignal } from '../simulation/farm-layout';

const SPRITE_KEY = 'cattle-atlas';

export class CowEntity {
  readonly sprite: Phaser.GameObjects.Sprite;
  readonly behavior: AnimalBehavior;
  private readonly selection: Phaser.GameObjects.Arc;
  private readonly pasture: PastureZone;
  private lastFrame = -1;
  private snapshot: BehaviorSnapshot;
  private motionTime = 0;

  constructor(
    private readonly scene: Phaser.Scene,
    readonly index: number,
    pasture: PastureZone,
    onSelect: () => void,
  ) {
    this.pasture = pasture;
    this.behavior = new AnimalBehavior(index, pasture);
    this.snapshot = this.behavior.current;
    this.sprite = scene.add.sprite(this.snapshot.x, this.snapshot.y, SPRITE_KEY, this.frameFor(this.snapshot.status, index % 4, index % 4))
      .setOrigin(0.5, 0.72)
      .setDepth(this.snapshot.y)
      .setInteractive({ useHandCursor: true });
    this.sprite.on('pointerdown', (pointer: Phaser.Input.Pointer) => {
      pointer.event.stopPropagation();
      onSelect();
    });
    this.selection = scene.add.circle(this.snapshot.x, this.snapshot.y + 5, 13, 0x20312b, 0.13)
      .setStrokeStyle(2, 0x344b3e, 0.75)
      .setDepth(this.snapshot.y - 1)
      .setVisible(false);
    this.applyStatus(this.snapshot.status);
  }

  update(deltaMs: number, reducedMotion: boolean): void {
    this.snapshot = this.behavior.update(deltaMs, reducedMotion);
    if (!reducedMotion) this.motionTime += Math.min(deltaMs, 50);
    const { x, y, status, heading } = this.snapshot;
    this.sprite.setPosition(x, y).setDepth(y + 1);
    this.selection.setPosition(x, y + 5).setDepth(y);
    if (reducedMotion) {
      this.sprite.setRotation(0).setScale(1, 1);
    } else if (status === 'WALK') {
      this.sprite.setRotation(Math.sin(heading) * 0.07)
        .setScale(1, 0.97 + Math.abs(Math.sin(this.motionTime * 0.012 + this.index)) * 0.06);
      this.sprite.setFlipX(Math.cos(heading) < 0);
    } else if (status === 'GRAZE') {
      this.sprite.setRotation(Math.sin(this.motionTime * 0.002 + this.index) * 0.035).setScale(1, 1);
    } else {
      this.sprite.setRotation(0).setScale(1, 1);
    }
    this.applyStatus(status);
  }

  setSelected(selected: boolean): void {
    this.selection.setVisible(selected);
    this.sprite.setAlpha(selected ? 1 : 0.94);
  }

  getState(): AnimalState {
    return {
      id: `animal-${this.index}`,
      label: `Animal ${this.index}`,
      status: this.snapshot.status,
      zone: this.pastureName,
      estimatedPosition: { x: Math.round(this.snapshot.x), y: Math.round(this.snapshot.y) },
      signalLevel: classifySignal(this.snapshot.x, this.snapshot.y),
    };
  }

  destroy(): void {
    this.sprite.destroy();
    this.selection.destroy();
  }

  private get pastureName(): string { return this.pasture.name; }

  private applyStatus(status: BehaviorSnapshot['status']): void {
    const nextFrame = this.frameFor(status, this.index % 4, this.directionFor(this.snapshot.heading));
    if (this.lastFrame !== nextFrame) {
      this.sprite.setFrame(nextFrame);
      this.lastFrame = nextFrame;
    }
  }

  private frameFor(status: BehaviorSnapshot['status'], coat: number, direction: number): number {
    // Atlas generated by tools/generate_assets.py: 4 coats x 4 directions x
    // 5 actions x 2 frames, packed in row-major 16-column 32px cells.
    const action = status === 'GRAZE' ? 1 : status === 'WALK' ? 2 : status === 'DRINK' ? 3 : 0;
    const frame = Math.floor(this.motionTime / (status === 'WALK' ? 220 : 620)) % 2;
    return (((coat * 4 + direction) * 5 + action) * 2) + frame;
  }

  private directionFor(heading: number): number {
    return (Math.round(heading / (Math.PI / 2)) + 1 + 4) % 4;
  }
}
